CREATE DATABASE TRABALHO22;
USE TRABALHO22;

##DROP DATABASE TRABALHO22


/* Deivison Albring, José perlin, Rodrigo Batista, 
Rodrigo Magalski, Rafael Braga, Luis Balesteri, 
Lucas Carvalho, Matheus Manfio, Gabriel Balestrin
*/


CREATE TABLE TIPO_VEI(
	
    COD_TIPO INT PRIMARY KEY AUTO_INCREMENT,
    DESC_TIPO VARCHAR(255)
);


INSERT INTO TIPO_VEI(DESC_TIPO) VALUES ('Carro');
INSERT INTO TIPO_VEI(DESC_TIPO) VALUES ('Moto');
INSERT INTO TIPO_VEI (DESC_TIPO)VALUES ('Onibus');

CREATE TABLE VAGA(

	COD_VAGA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESC_VAGA VARCHAR(255),
    COD_TIPO INT, FOREIGN KEY (COD_TIPO) REFERENCES TIPO_VEI(COD_TIPO)    
);

INSERT INTO VAGA(DESC_VAGA,COD_TIPO) VALUES('DEFICIENTE',1);
INSERT INTO VAGA(DESC_VAGA,COD_TIPO) VALUES('IDOSO',2);
INSERT INTO VAGA (DESC_VAGA,COD_TIPO)VALUES('NORMAL',3);

CREATE TABLE MARCA(
	
    COD_MARCA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_MARCA VARCHAR(255)
);

INSERT INTO MARCA(NOME_MARCA) VALUES ('VOLKSWAGEN');
INSERT INTO MARCA(NOME_MARCA) VALUES ('CHEVROLET');
INSERT INTO MARCA(NOME_MARCA)VALUES ('FIAT');
INSERT INTO MARCA(NOME_MARCA) VALUES ('FORD');

CREATE TABLE COR(
	
	COD_COR INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	DESC_COR VARCHAR(255)
);

INSERT INTO COR(DESC_COR) VALUES ('BRANCO');
INSERT INTO COR(DESC_COR) VALUES ('VERMELHO');
INSERT INTO COR(DESC_COR) VALUES ('AMARELO');
INSERT INTO COR(DESC_COR) VALUES ('PRETO');

CREATE TABLE PESSOA(

	COD_PES INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_PES VARCHAR(255),
    SEXO_PES VARCHAR(255),
    DATA_NASC DATE,
    CPF_PES VARCHAR(255)    
);

INSERT INTO PESSOA(NOME_PES,SEXO_PES,DATA_NASC,CPF_PES) VALUES('MATEUS', 'MASCULINO', '1999/11/22', '12345678910');
INSERT INTO PESSOA(NOME_PES,SEXO_PES,DATA_NASC,CPF_PES) VALUES('GABRIEL', 'FEMININO','1924/04/24', '55544433312');
INSERT INTO PESSOA(NOME_PES,SEXO_PES,DATA_NASC,CPF_PES) VALUES('JOSÉ', 'INDEFINIDO', '1998/12/24', '99988866648');

CREATE TABLE PES_TIPOS(
	
	COD_TIPO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESC_TIPOS VARCHAR(255)
);

INSERT INTO PES_TIPOS(DESC_TIPOS) VALUES('PROFESSOR');
INSERT INTO PES_TIPOS(DESC_TIPOS) VALUES('ALUNO');
INSERT INTO PES_TIPOS(DESC_TIPOS) VALUES('FUNCIONÁRIO');

CREATE TABLE STATUS (
	
    COD_STA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESC_STA VARCHAR(255)
);

INSERT INTO STATUS(DESC_STA) VALUES('DESABILITADO');
INSERT INTO STATUS(DESC_STA) VALUES('HABILITADO');
INSERT INTO STATUS(DESC_STA) VALUES('MANUTENÇÃO');

CREATE TABLE DEPARTAMENTOS(
	
    COD_DPTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_DPTO VARCHAR(255)
);

INSERT INTO DEPARTAMENTOS(NOME_DPTO) VALUES('ENGENHARIA E CIENCIA DA COMPUTAÇÃO');
INSERT INTO DEPARTAMENTOS(NOME_DPTO) VALUES('SAÚDE');
INSERT INTO DEPARTAMENTOS(NOME_DPTO) VALUES('EXATAS');

CREATE TABLE CURSO (

	COD_CURSO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME_CURSO VARCHAR(255),
    COD_DPTO INT, FOREIGN KEY (COD_DPTO) REFERENCES DEPARTAMENTOS(COD_DPTO)
    
);

INSERT INTO CURSO(NOME_CURSO,COD_DPTO) VALUES('CIENCIA DA COMPUTAÇÃO',1);
INSERT INTO CURSO(NOME_CURSO,COD_DPTO) VALUES('ADMINISTRAÇÃO',2);
INSERT INTO CURSO(NOME_CURSO,COD_DPTO) VALUES('CONTABILIDADE',3);

CREATE TABLE BLOCO(
	
	COD_BLOCO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    BLOCO VARCHAR(15),
    ANDAR INT
    
);

INSERT INTO BLOCO(BLOCO,ANDAR) VALUES('A',1);
INSERT INTO BLOCO(BLOCO,ANDAR) VALUES('B',2);
INSERT INTO BLOCO(BLOCO,ANDAR) VALUES('C',3);
INSERT INTO BLOCO(BLOCO,ANDAR) VALUES('D',4);


CREATE TABLE SALAS (

	COD_SALA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NUMERO_SALA INT,
    COD_STA INT, FOREIGN KEY (COD_STA) REFERENCES STATUS(COD_STA),
    COD_BLOCO INT, FOREIGN KEY (COD_BLOCO) REFERENCES BLOCO(COD_BLOCO),
    COD_CURSO INT, FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO)
    
);

INSERT INTO SALAS(NUMERO_SALA,COD_STA,COD_BLOCO,COD_CURSO) VALUES('301', 1,1, 1);
INSERT INTO SALAS(NUMERO_SALA,COD_STA,COD_BLOCO,COD_CURSO) VALUES('303', 2,2, 2);
INSERT INTO SALAS(NUMERO_SALA,COD_STA,COD_BLOCO,COD_CURSO) VALUES('303', 3,3, 3);

CREATE TABLE EQUIPAMENTOS(

	COD_EQUIP INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESC_EQUIP VARCHAR(255),
    COD_STA INT, FOREIGN KEY (COD_STA) REFERENCES STATUS(COD_STA),
    COD_SALA INT, FOREIGN KEY (COD_SALA) REFERENCES SALAS(COD_SALA)
);

INSERT INTO EQUIPAMENTOS(DESC_EQUIP,COD_STA,COD_SALA) VALUES('COMPUTADOR', 1, 1);
INSERT INTO EQUIPAMENTOS(DESC_EQUIP,COD_STA,COD_SALA) VALUES('IMPRESSORA', 2, 2);
INSERT INTO EQUIPAMENTOS(DESC_EQUIP,COD_STA,COD_SALA) VALUES('PROJETOR', 3, 3);

CREATE TABLE PROFESSOR (

	COD_PROF INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_PES INT, FOREIGN KEY (COD_PES) REFERENCES PESSOA(COD_PES),
    COD_CURSO INT, FOREIGN KEY (COD_CURSO) REFERENCES CURSO(COD_CURSO),
    COD_SALA INT, FOREIGN KEY (COD_SALA) REFERENCES SALAS(COD_SALA),
    COD_TIPO INT, FOREIGN KEY (COD_TIPO) REFERENCES PES_TIPOS(COD_TIPO)  
	
);

INSERT INTO PROFESSOR(COD_PES,COD_CURSO,COD_SALA,COD_TIPO) VALUES(1, 1, 1,1);
INSERT INTO PROFESSOR(COD_PES,COD_CURSO,COD_SALA,COD_TIPO) VALUES(2, 2, 2,2);
INSERT INTO PROFESSOR(COD_PES,COD_CURSO,COD_SALA,COD_TIPO) VALUES(3, 3, 3,3);


CREATE TABLE VEICULO(
	
	COD_VEI INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    COD_MARCA INT, FOREIGN KEY (COD_MARCA) REFERENCES MARCA(COD_MARCA),
    COD_COR INT, FOREIGN KEY (COD_COR) REFERENCES COR(COD_COR),
    COD_VAGA INT, FOREIGN KEY (COD_VAGA) REFERENCES VAGA(COD_VAGA),
    PLACA_VEI VARCHAR(255),
    COD_TIPO INT, FOREIGN KEY (COD_TIPO) REFERENCES TIPO_VEI(COD_TIPO),
    COD_PES INT, FOREIGN KEY (COD_PES) REFERENCES PESSOA(COD_PES)
);

INSERT INTO VEICULO(COD_MARCA,COD_COR,COD_VAGA,PLACA_VEI,COD_TIPO,COD_PES) VALUES(1,1,1, 'APN-6580', 1,1);
INSERT INTO VEICULO(COD_MARCA,COD_COR,COD_VAGA,PLACA_VEI,COD_TIPO,COD_PES) VALUES(2,2,2, 'JAP-2555', 2,2);
INSERT INTO VEICULO(COD_MARCA,COD_COR,COD_VAGA,PLACA_VEI,COD_TIPO,COD_PES) VALUES(3,3,3, 'DCX-456', 3,3);


